### ISSUE TITLE
test env

### ISSUE THREAD

**Issue by coolcodemy** [Muhaimin/movie-app#1]
https://github.com/Muhaimin/movie-app/blob/9bf7c56c7eec6fa6fb50873084731ab788546ae9/phpunit.xml#L24-L25

Should use `sqlite` and `:memory:` for faster test execution without needing to set 3rd party dependency (db, webserver, etc)

**Comment by Muhaimin** [comment]
Noted, will implement it accordingly. I agree that sqlite and stored in memory will be much faster.
