### ISSUE TITLE
Test get bypassed because resource is created directly on the database

### ISSUE THREAD

**Issue by coolcodemy** [Muhaimin/movie-app#3]
https://github.com/Muhaimin/movie-app/blob/9bf7c56c7eec6fa6fb50873084731ab788546ae9/tests/Feature/CreateNewMovieTest.php#L60-L66

Using `->create()` will directly create to db instead of posting it to the create movie endpoint. use `->raw()` instead to generate fake name

the test should check if the created movie name is displayed after redirection, or check if it is exist on the database

**Comment by Muhaimin** [comment]
My bad 😅, I implement faker to generate name to fix the bypass.


```
public function user_can_create_new_movie(){

        //Create 1 user
        $user = User::factory()->create(['id' => '1']);
        $user->save();
        
        $faker = \Faker\Factory::create();

        $response = $this->post(route('movies.store'),[
            'name' => $faker->name(),
        ]);

        $response->assertRedirect(route('movies.index'));
        
    }
```

**Comment by coolcodemy** [comment]
Should use 

```
$movieRaw = Movie::factory()->raw();

$response = $this->post(route('movies.store'),[
    'name' => $movieRaw['name'],
]);

```

Since we already defined the structure of faking the model properties. Calling faker directly will defeat the purpose of generating factory for each model.
